/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package agendador;


import java.util.Calendar;


/**
 *
 * @author alexandre
 */
public class Agendador extends javax.swing.JFrame 
{

    Comunicador comunicador;
    /**
     * Creates new form Agendador
     */
//-----------------------------------------------------------------------------------------------------  
    public Agendador() 
    {
        initComponents();
        dpData.setFormats("dd/MM/yyyy");
        dpRelogioData.setFormats("dd/MM/yyyy");
        comunicador= new Comunicador();
        comunicador.Log=this.taLog;
    }
//-----------------------------------------------------------------------------------------------------
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgTipoAgendamento = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pDiario2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        btnEnviarRelogio = new javax.swing.JButton();
        btnPegarHoraPC = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        tfRelogio = new javax.swing.JTextField();
        dpRelogioData = new org.jdesktop.swingx.JXDatePicker();
        jScrollPane1 = new javax.swing.JScrollPane();
        taLog = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        pDiario = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnEnviarDiario = new javax.swing.JButton();
        tfDiarioHora = new javax.swing.JTextField();
        pData = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        dpData = new org.jdesktop.swingx.JXDatePicker();
        jLabel4 = new javax.swing.JLabel();
        btnEnviarData = new javax.swing.JButton();
        tfDataHora = new javax.swing.JTextField();
        rbMotor1 = new javax.swing.JRadioButton();
        rbMotor2 = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        listPorta = new javax.swing.JComboBox();
        btnIniciar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        jLabel1.setForeground(java.awt.Color.red);
        jLabel1.setText("Agendador");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(222, 222, 222))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        pDiario2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ajustar Relógio", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 24))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel6.setText("Hora:");

        btnEnviarRelogio.setText("Enviar");
        btnEnviarRelogio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEnviarRelogioMouseClicked(evt);
            }
        });

        btnPegarHoraPC.setText("Pegar Hora");
        btnPegarHoraPC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPegarHoraPCMouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel5.setText("Data:");

        tfRelogio.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        tfRelogio.setText("18:45");
        tfRelogio.setToolTipText("HH:MM");

        dpRelogioData.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N

        javax.swing.GroupLayout pDiario2Layout = new javax.swing.GroupLayout(pDiario2);
        pDiario2.setLayout(pDiario2Layout);
        pDiario2Layout.setHorizontalGroup(
            pDiario2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDiario2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(dpRelogioData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(4, 4, 4)
                .addComponent(tfRelogio, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(btnPegarHoraPC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEnviarRelogio))
        );
        pDiario2Layout.setVerticalGroup(
            pDiario2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDiario2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pDiario2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pDiario2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(dpRelogioData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pDiario2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnEnviarRelogio)
                        .addComponent(btnPegarHoraPC))
                    .addComponent(jLabel6))
                .addContainerGap(16, Short.MAX_VALUE))
            .addGroup(pDiario2Layout.createSequentialGroup()
                .addComponent(tfRelogio, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        taLog.setColumns(20);
        taLog.setRows(5);
        jScrollPane1.setViewportView(taLog);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Agendamento", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 24))); // NOI18N
        jPanel2.setToolTipText("Agendamento");

        pDiario.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Diário", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 18))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel2.setText("Hora do dia:");

        btnEnviarDiario.setText("Enviar");
        btnEnviarDiario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEnviarDiarioMouseClicked(evt);
            }
        });

        tfDiarioHora.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        tfDiarioHora.setText("16:51");
        tfDiarioHora.setToolTipText("HH:MM");

        javax.swing.GroupLayout pDiarioLayout = new javax.swing.GroupLayout(pDiario);
        pDiario.setLayout(pDiarioLayout);
        pDiarioLayout.setHorizontalGroup(
            pDiarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDiarioLayout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(jLabel2)
                .addGap(3, 3, 3)
                .addComponent(tfDiarioHora, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEnviarDiario)
                .addContainerGap())
        );
        pDiarioLayout.setVerticalGroup(
            pDiarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDiarioLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(pDiarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfDiarioHora, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEnviarDiario)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pData.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Data", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 18))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel3.setText("Data:");

        dpData.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel4.setText("Hora:");

        btnEnviarData.setText("Enviar");
        btnEnviarData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEnviarDataMouseClicked(evt);
            }
        });

        tfDataHora.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        tfDataHora.setText("18:45");
        tfDataHora.setToolTipText("HH:MM");

        javax.swing.GroupLayout pDataLayout = new javax.swing.GroupLayout(pData);
        pData.setLayout(pDataLayout);
        pDataLayout.setHorizontalGroup(
            pDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDataLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dpData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel4)
                .addGap(3, 3, 3)
                .addComponent(tfDataHora, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEnviarData)
                .addContainerGap())
        );
        pDataLayout.setVerticalGroup(
            pDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDataLayout.createSequentialGroup()
                .addGroup(pDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pDataLayout.createSequentialGroup()
                            .addGap(24, 24, 24)
                            .addGroup(pDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(dpData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pDataLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(btnEnviarData)))
                    .addGroup(pDataLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tfDataHora, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        buttonGroup1.add(rbMotor1);
        rbMotor1.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        rbMotor1.setSelected(true);
        rbMotor1.setText("Motor 1");

        buttonGroup1.add(rbMotor2);
        rbMotor2.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        rbMotor2.setText("Motor 2");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pDiario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(rbMotor1)
                        .addGap(18, 18, 18)
                        .addComponent(rbMotor2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbMotor1)
                    .addComponent(rbMotor2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(pDiario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Comunicacão", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 24))); // NOI18N

        jLabel11.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel11.setText("Porta:");

        listPorta.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N

        btnIniciar.setText("Iniciar");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(listPorta, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnIniciar)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(btnIniciar)
                    .addComponent(listPorta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pDiario2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pDiario2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//-----------------------------------------------------------------------------------------------------
    private void btnPegarHoraPCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPegarHoraPCMouseClicked
        Calendar now=Calendar.getInstance();
        
        tfRelogio.setText(String.format("%02d:%02d:%02d", now.get(Calendar.HOUR_OF_DAY),
                now.get(Calendar.MINUTE), now.get(Calendar.SECOND)));
        dpRelogioData.setDate(now.getTime());
    }//GEN-LAST:event_btnPegarHoraPCMouseClicked
//-----------------------------------------------------------------------------------------------------
    private void btnEnviarDiarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEnviarDiarioMouseClicked
       
        
        String[] tmp=tfDiarioHora.getText().split(":");
        
        System.out.println(tfDiarioHora.getText());
        
        if(rbMotor1.isSelected())
            comunicador.AgendarDiario(Integer.parseInt(tmp[0]), 
                                      Integer.parseInt(tmp[1]), 
                                      1);
        else
            comunicador.AgendarDiario(Integer.parseInt(tmp[0]), 
                                      Integer.parseInt(tmp[1]), 
                                      2);
    }//GEN-LAST:event_btnEnviarDiarioMouseClicked

    private void btnEnviarDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEnviarDataMouseClicked
        String[] tmp=tfDataHora.getText().split(":");
        
        System.out.println(tfDataHora.getText());        
        Calendar calendar= Calendar.getInstance();        
        calendar.setTime(dpData.getDate());
        
        
        if(rbMotor1.isSelected())
            comunicador.AgendarData(calendar.get(Calendar.DAY_OF_MONTH),
                                    calendar.get(Calendar.MONTH),
                                    calendar.get(Calendar.YEAR),
                                    Integer.parseInt(tmp[0]), 
                                    Integer.parseInt(tmp[1]), 
                                    1);
        else
            comunicador.AgendarData(calendar.get(Calendar.DAY_OF_MONTH),
                                    calendar.get(Calendar.MONTH),
                                    calendar.get(Calendar.YEAR),
                                    Integer.parseInt(tmp[0]), 
                                    Integer.parseInt(tmp[1]), 
                                    2);
    }//GEN-LAST:event_btnEnviarDataMouseClicked

    private void btnEnviarRelogioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEnviarRelogioMouseClicked
        String[] tmp=tfDataHora.getText().split(":");
        
        System.out.println(tfRelogio.getText());
        
        Calendar calendar= Calendar.getInstance();        
        calendar.setTime(dpRelogioData.getDate());
        
       
        comunicador.EnviarRelogio(calendar.get(Calendar.DAY_OF_MONTH),
                                  calendar.get(Calendar.MONTH),
                                  calendar.get(Calendar.YEAR),
                                  Integer.parseInt(tmp[0]), 
                                  Integer.parseInt(tmp[1])
                                  ,0);
     
    }//GEN-LAST:event_btnEnviarRelogioMouseClicked
//-----------------------------------------------------------------------------------------------------
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agendador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agendador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agendador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agendador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               Agendador agendador = new Agendador();
               agendador.setVisible(true);
                              
            }
        });
    }
//-----------------------------------------------------------------------------------------------------
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgTipoAgendamento;
    private javax.swing.JButton btnEnviarData;
    private javax.swing.JButton btnEnviarDiario;
    private javax.swing.JButton btnEnviarRelogio;
    private javax.swing.JButton btnIniciar;
    private javax.swing.JButton btnPegarHoraPC;
    private javax.swing.ButtonGroup buttonGroup1;
    private org.jdesktop.swingx.JXDatePicker dpData;
    private org.jdesktop.swingx.JXDatePicker dpRelogioData;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox listPorta;
    private javax.swing.JPanel pData;
    private javax.swing.JPanel pDiario;
    private javax.swing.JPanel pDiario2;
    private javax.swing.JRadioButton rbMotor1;
    private javax.swing.JRadioButton rbMotor2;
    private javax.swing.JTextArea taLog;
    private javax.swing.JTextField tfDataHora;
    private javax.swing.JTextField tfDiarioHora;
    private javax.swing.JTextField tfRelogio;
    // End of variables declaration//GEN-END:variables
}
